#!/bin/sh

# PROVIDE: b16
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr                      # required by rc.d subsystem

name="b16"                          # name of script
rcvar="b16_enable"                  # name of /etc/rc.conf enable command
command="/usr/local/sbin/${name}"   # path to executable
command_args="&"                    # arguments to executable
#pidfile="/var/run/${name}.pid"     # file containing service's process ID
required_files=""                   # files required to start service
#start_cmd="${name}_start"          # name of start function
#stop_cmd="${name}_stop"            # name of stop function

load_rc_config $name                # load rc.conf variables
: ${b16_enable:=yes}                # enable by default
: ${b16_startmsgs:=yes}             # show startup messages in /var/log/syslog

b16_start() {
    # unused 
}

b16_stop() {
    # unused
}

run_rc_command "$1"                 # invoke rc.subr

