#!/bin/sh

# PROVIDE: EmergencyBrake
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr                      # required by rc.d subsystem

name="EmergencyBrake"               # name of script
rcvar="EmergencyBrake_enable"       # name of /etc/rc.conf enable command
command="/usr/local/sbin/${name}"   # path to executable
command_args="&"                    # arguments to executable
#pidfile="/var/run/${name}.pid"     # file containing service's process ID
required_files=""                   # files required to start service
#start_cmd="${name}_start"          # name of start function
#stop_cmd="${name}_stop"            # name of stop function

load_rc_config $name                # load rc.conf variables
: ${EmergencyBrake_enable:=yes}     # enable by default
: ${EmergencyBrake_startmsgs:=yes}  # show startup messages in /var/log/syslog

EmergencyBrake_start() {
    # unused 
}

EmergencyBrake_stop() {
    # unused
}

run_rc_command "$1"                 # invoke rc.subr

