#!/bin/sh

# PROVIDE: sheepster
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr                      # required by rc.d subsystem

name="sheepster"                    # name of script
rcvar="sheepster_enable"            # name of /etc/rc.conf enable command
command="/usr/local/sbin/${name}"   # path to executable
command_args="&"                    # arguments to executable
#pidfile="/var/run/${name}.pid"     # file containing service's process ID
required_files=""                   # files required to start service
#start_cmd="${name}_start"          # name of start function
#stop_cmd="${name}_stop"            # name of stop function

load_rc_config $name                # load rc.conf variables
: ${sheepster_enable:=yes}          # enable by default
: ${sheepster_startmsgs:=yes}       # show startup messages in /var/log/syslog

sheepster_start() {
    # unused 
}

sheepster_stop() {
    # unused
}

run_rc_command "$1"                 # invoke rc.subr

