#!/bin/sh

# PROVIDE: SERVICE_NAME
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr                      # required by rc.d subsystem

name="SERVICE_NAME"                 # name of script
rcvar="SERVICE_NAME_enable"         # name of /etc/rc.conf enable command
command="/usr/local/sbin/${name}"   # path to executable
command_args="&"                    # arguments to executable
#pidfile="/var/run/${name}.pid"     # file containing service's process ID
required_files=""                   # files required to start service
#start_cmd="${name}_start"          # name of start function
#stop_cmd="${name}_stop"            # name of stop function

load_rc_config $name                # load rc.conf variables
: ${SERVICE_NAME_enable:=yes}       # enable by default
: ${SERVICE_NAME_startmsgs:=yes}    # show startup messages in /var/log/syslog

SERVICE_NAME_start() {
    # unused 
}

SERVICE_NAME_stop() {
    # unused
}

run_rc_command "$1"                 # invoke rc.subr

